### ISSUE TITLE
Export schlägt fehl mit Proxy

### ISSUE THREAD

**Issue by SebaDro** [KomMonitor/web-client#36]
**Beschreibung**
Wird der Web Client hinter einem Proxy betrieben und ist über einen Unterpfad erreichbar, z.B. https://localhost/kommonitor, schlägt der Export für jede der vier Optionen (Metadatentabelle, GeoJSON, ESRI Shape, CSV) mit folgender Fehlermeldung fehl:
```
GET https://localhost/logos/KM_Logo1.png 404 (Not Found)
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at t.__addimage__.getImageFileTypeByImageData (addimage.js:144:18)
    at Object.P (addimage.js:892:14)
    at t.addImage (addimage.js:855:34)
    at Object.<anonymous> (kommonitor-client.min.js:3:58027)
    at e (polyfill.min.js:1:95273)
    at Generator._invoke (polyfill.min.js:1:95061)
    at forEach.t.<computed> [as next] (polyfill.min.js:1:95453)
    at r (kommonitor-client.min.js:3:1250)
    at kommonitor-client.min.js:3:1389
    at new Promise (<anonymous>)
```
**Reproduzieren**
Um den Fehler zu reproduzieren muss der Web Client hinter einem Proxy betrieben werden, und über einen Unterpfad erreichbar sein, z.B. https://localhost/kommonitor. Danach folgende Schritte durchführen:
1. Web Client aufrufen
2. Ggf. anmelden, falls keine öffentlichen Daten verfügbar sind
3. Aufruf einer der vier Exportfunktionen (Klick auf Button "Metadatentabelle", "GeoJSON", "ESRI Shape" oder "CSV")
4. Es erfolgt kein Export. Stattdessen wird o.a. Fehlermeldung auf der Console ausgegeben

**Lösungsansatz**
Wie man an der Fehlermeldung erkennt, versucht der Web Client für die Generierung des Metadaten PDF das KomMonitor Logo zu laden, berücksichtigt dabei jedoch nicht den Unterpfad des Proxy. D.h. statt _https://localhost/kommonitor/logos/KM_Logo1.png_ wird der Pfad _https://localhost/logos/KM_Logo1.png_ aufgerufen. Unter diesem Pfad ist das Logo jedoch nicht abrufbar. Das Problem tritt hier
https://github.com/KomMonitor/web-client/blob/db4431f39133d119ff77330157603df2606ea5a6/app/util/genericServices/kommonitorDataExchangeService/kommonitor-data-exchange-service.module.js#L2117-L2118
und hier auf
https://github.com/KomMonitor/web-client/blob/db4431f39133d119ff77330157603df2606ea5a6/app/util/genericServices/kommonitorDataExchangeService/kommonitor-data-exchange-service.module.js#L2444-L2445

Zur Behebung könnte entweder der aktuelle Subpfad der URL ermittelt werden und der URL für das Logo als Prefix hinzugefügt werden oder es wird ein Konfigurationsparameter aufgenommen, der es erlaubt einen Subpfad anzugeben, der dann als Prefix der Logo URL hinzugefügt wird.

**Comment by SebaDro** [comment]
Commit #44117354 sollte das Problem beheben.
